"""add email in paciente

Revision ID: 38355139ea85
Revises: 
Create Date: 2025-09-04 11:49:43.373378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38355139ea85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
